# backend/config/symbols.py

# Top 50 USDT perpetual futures pairs (initial universe)

SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "ADAUSDT", "SOLUSDT",
    "XRPUSDT", "LTCUSDT", "DOTUSDT", "DOGEUSDT", "MATICUSDT",
    "AVAXUSDT", "LINKUSDT", "UNIUSDT", "ATOMUSDT", "ALGOUSDT",
    "VETUSDT", "FILUSDT", "ICPUSDT", "MANAUSDT", "SANDUSDT",
    "AAVEUSDT", "NEOUSDT", "XTZUSDT", "THETAUSDT", "TRXUSDT",
    "EGLDUSDT", "FLOWUSDT", "KSMUSDT", "CHZUSDT", "FTMUSDT",
    "HNTUSDT", "RUNEUSDT", "CAKEUSDT", "SUSHIUSDT", "GRTUSDT",
    "1INCHUSDT", "EOSUSDT", "BCHUSDT", "ZILUSDT", "QTUMUSDT",
    "STXUSDT", "KAVAUSDT", "CELOUSDT", "ONTUSDT", "ANKRUSDT",
    "RLCUSDT", "LRCUSDT", "DASHUSDT", "BATUSDT", "ICXUSDT"
]
